# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[git_branch]
symbol = ' '

[nodejs]
format = '[  $version]($style)'

[deno]
format = '[🦖  $version]($style)'

[lua]
format = '[󰢱  version]($style)'

[package]
format = '[$symbol$version]($style) '
symbol = ' '

[directory]
truncate_to_repo = false
