theme = "catppuccin_mocha"

[editor]
mouse = true
rulers = [80]
auto-format = true
color-modes = true
bufferline = "always"

[editor.statusline]
left = [ "mode", "spacer", "version-control", "spacer", "file-modification-indicator", "spacer", "spinner" ]
center = ["file-base-name"]

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace]
reder = "all"

[editor.auto-pairs]
'<' = '>'
'(' = ')'
'{' = '}'
'[' = ']'
'`' = '`'
'"' = '"'
"'" = "'"

[keys.normal.g] 
"h" = "goto_first_nonwhitespace"

[keys.normal.space]
q = ":qa"
"=" = ":format"
"u" = ":u"
"x" = ":bc"
"o" = ":bco"
