# Prettier formats: js, jsx, ts, tsx, json, html, css, markdown
[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.js"] }

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.jsx"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.ts"] }

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.tsx"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.json"] }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.html"] }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.css"] }

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--stdin-filepath", "file.md"] }
