[language-server.emmet-ls]
command = "emmet-ls"
args = [ "--stdio" ]
name = "emmet-ls"
file-types = ["tsx", "jsx", "html"]
language-server = { command = "emmet-ls" }

[language-server.astro-ls]
command = "astro-ls"
args = [ "--stdio" ]
config = { typescript = { tsdk = "node_modules/typescript/lib" } }

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
block-comment-tokens = { start = "<!--", end = "-->" }
indent = { tab-width = 2, unit = "  " }
language-servers = [ "astro-ls" ]
auto-format = true
formatter = { command = "prettierd", args = ["--stdin-filepath", "%{buffer_name}"] }

[[grammar]]
name = "astro"
source = { git = "https://github.com/virchau13/tree-sitter-astro", rev = "947e93089e60c66e681eba22283f4037841451e7" }# [[language]]
