#!/usr/bin/env bash

# Use `fd` as the source. It respects .gitignore by default.
# We also explicitly exclude .git and node_modules.
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix --exclude .git --exclude node_modules"

export FZF_DEFAULT_OPTS="
  --info inline --padding 2 --reverse
  --color bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796
  --color fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6
  --color marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796
  --prompt '󰍉  ' --marker '󰄬 ' --pointer ' ' --separator '─'
  --scrollbar '┃'
  --height 100%
"

# Ctrl-T: files via fd (same filters)
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --multi
  --bind 'ctrl-/:change-preview-window(down|hidden|)'
  --bind 'enter:execute(nvim {+})'
"

# Alt-C: directories via fd (same filters)
export FZF_ALT_C_COMMAND="fd --type d --strip-cwd-prefix --exclude .git --exclude node_modules"
export FZF_ALT_C_OPTS="
  --preview 'tree -L 1 -C {}'
"

. <(fzf --zsh)
