set -g mode-keys vi
set -g base-index  1
set -g renumber-windows on
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g status-left "#S"
set -g status-right ""
set -g window-status-current-style "fg=green bold"
set -g allow-rename off
# set -g default-terminal "tmux-256color"
# set -as terminal-features 'tmux-256color:RGB'

bind r source-file ~/.config/tmux/tmux.conf\; \
display-message "Config reloaded"

# Vim motions for panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use pbcopy for copying to system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
set-option -g focus-events on

unbind M-u
bind C-I run-shell ~/.tmux/plugins/tpm/bin/clean_plugins
# bind -n C-e neww -n "Yazi" yazi
bind -n C-e neww -n "Superfile" spf
bind -n C-g neww -n" Lazygit" lazygit
bind -n C-s neww -n "Serpl" serpl 
